version: '3.8'

services:
  frontend:
    container_name: fylt_web
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  backend:
    container_name: fylt_api
    build:
      context: ./net
      dockerfile: Fylt.Api/Dockerfile
    ports:
      - "7052:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7052/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
